name: Test application

on:
  pull_request:
    branches: [master, qa]

jobs:
  pr-checker:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    outputs:
      canSkip: ${{ steps.Checker.outputs.canSkip }}
    steps:
      - name: Get files
        uses: actions/checkout@v2
      - name: Get tools
        uses: actions/checkout@v2
        with:
          path: tools/
          repository: openliberty/guides-common
          ref: pr-checker
      - name: Checker
        run: sh tools/pr-checker/checker.sh ${{ github.repository }} ${{ github.event.pull_request.number }}
      - name: Lint Code Base
        uses: github/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: ./tools/pr-checker/linters/
      - name: Upload checker logs
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: checker-log
          path: ./super-linter.log
         
  java8build:
    runs-on: ubuntu-latest
    needs: [pr-checker]
    if: "!contains(needs.pr-checker.outputs.canSkip, 'true')"
    defaults:
      run:
        working-directory: finish
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - run: unset _JAVA_OPTIONS
    - name: Run tests
      run: ../scripts/testApp.sh
    - name: Post tests
      if: always()
      run: |
           docker images
           logsPath=$(find . -name "console.log");
           cat $logsPath | grep Launching
    - name: Archive server logs if failed
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: server-logs
        path: finish/target/liberty/wlp/usr/servers/defaultServer/logs/

